#! /bin/sh
# /etc/init.d/pihole-control

### BEGIN INIT INFO
# Provides:          pihole-control
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Startup script for pihole-control daemon
# Description:       A simple script for the Hexapod project that will start / stop the pihole-control Daemon
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting pihole-control daemon"
    /usr/local/bin/node /home/pi/git/pihole-control/bin/www >> /var/log/pihole-control.log 2>&1
    ;;
  stop)
    echo "Stopping pihole-control daemon"
    killall node
    ;;
  *)
    echo "Usage: /etc/init.d/pihole-control {start|stop}"
    exit 1
    ;;
esac

exit 0

